alter table TASKMAN_TASK_MESSAGE add constraint FK_TASKMAN_TASK_MESSAGE_ON_IMAP_MESSAGE foreign key (IMAP_MESSAGE_ID) references IMAP_MESSAGE(ID);
create index IDX_TASKMAN_TASK_MESSAGE_ON_IMAP_MESSAGE on TASKMAN_TASK_MESSAGE (IMAP_MESSAGE_ID);
